### ISSUE TITLE
release.linux-amd64.0.0.7.zip downloads Ethereum blockchain and not Akroma blockchain 

### ISSUE THREAD

**Issue by VERTlG0** [akroma-project/akroma#15]
I just downloaded the zip file for linux which only contained "geth". Ran it with default options to find out it DOES NOT create a .akroma directory for its blockchain and I also found out it downloads the Ethereum blockchain and not its own Akroma blockchain.  I verified this by attach the console and checking the blocks as it was syncing.. I then saw high number blocks in the 4,000,000 and 5,000,000 range verifying it was the ethereum blockchain and not the very small Akroma blockchain. I had to add the datadir option to explicity set it to .akroma.. leaving this out defaults to .ethereum dir which again shows me this is downloading the ethereum blockchain.

**Comment by detroitpro** [comment]
Please make sure you don't have geth in your path.

After you download and unzip and chmod geth. Start geth like so:

`./geth`

notice the `./`

I just downloaded and tested release.linux-amd64.0.0.7.zip. The `ChainID: 200625` ensures you are connected to the Akroma network. When you start geth, check the chain id.

```
detroitpro@detroitpro-laptop:~/Downloads/test$ unzip release.linux-amd64.0.0.7.zip 
Archive:  release.linux-amd64.0.0.7.zip
  inflating: geth                    
detroitpro@detroitpro-laptop:~/Downloads/test$ chmod 755 geth 
detroitpro@detroitpro-laptop:~/Downloads/test$ ./geth 
INFO [02-23|10:01:22] Starting peer-to-peer node               instance=Geth/v0.0.7-akroma-dfdbd426/linux-amd64/go1.9.2
INFO [02-23|10:01:22] Allocated cache and file handles         database=/home/detroitpro/.akroma/geth/chaindata cache=128 handles=1024
INFO [02-23|10:01:22] Initialised chain configuration          config="{ChainID: 200625 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 1 EIP158: 1 Byzantium: 0 Akroma: 300000 Engine: ethas
```

**Comment by VERTlG0** [comment]
I just closed the issue as you replied for that reason. I forgot the "./"
